'use client';

import { useRouter } from 'next/navigation';
import { useTeamPlanning } from '@/lib/teamPlanningContext';
import { useTravelAuth } from '@/components/travel/useTravelAuth';
import { api } from '@/lib/api';
import { useEffect, useState } from 'react';
import type { TeamDetail } from '@/lib/api';
import {
  MapPin, Calendar, DollarSign, CheckCircle2, XCircle, Crown,
  Shield, ThumbsUp, ThumbsDown, Loader2, Plane, AlertCircle,
} from 'lucide-react';

export default function ApprovePlanInner() {
  const { user, loading } = useTravelAuth();
  const {
    generatedPlan, memberVotes, setVote, leaderApproved, setLeaderApproved,
    canFinalApprove, coLeaderId, activeTeamId, unlockStage,
  } = useTeamPlanning();
  const router = useRouter();
  const [teamDetail, setTeamDetail] = useState<TeamDetail | null>(null);
  const [approving, setApproving] = useState(false);

  useEffect(() => {
    if (!activeTeamId) return;
    api.getTeam(activeTeamId).then(setTeamDetail).catch(() => {});
  }, [activeTeamId]);

  const leaderId = teamDetail?.createdBy ?? teamDetail?.members[0]?.userId ?? '';
  const currentUserId = user?.sub ?? '';
  const isAuthorized = canFinalApprove(currentUserId, leaderId);
  const myVote = memberVotes[currentUserId];

  const approveCount = Object.values(memberVotes).filter(v => v === 'approve').length;
  const rejectCount = Object.values(memberVotes).filter(v => v === 'reject').length;
  const totalVotes = Object.keys(memberVotes).length;

  const handleFinalApprove = async () => {
    setApproving(true);
    await new Promise(r => setTimeout(r, 800)); // slight delay for feel
    setLeaderApproved(true);
    unlockStage('travel');
    setApproving(false);
    router.push('/travel-plan');
  };

  if (loading || !user) {
    return <div className="py-24 text-center text-sm text-gray-400">Signing you in…</div>;
  }

  if (!generatedPlan) {
    return (
      <div className="flex flex-col items-center justify-center py-20 gap-4 text-center">
        <div className="w-16 h-16 rounded-full bg-gray-100 flex items-center justify-center">
          <AlertCircle className="w-8 h-8 text-gray-400" />
        </div>
        <div>
          <h3 className="text-lg font-bold text-gray-800 mb-1">No plan yet</h3>
          <p className="text-sm text-gray-500">Go to the <span className="font-semibold text-violet-600">Plan</span> room and say &quot;I agree&quot; when the agents finish discussing.</p>
        </div>
        <button
          onClick={() => router.push('/plan')}
          className="px-5 py-2.5 bg-violet-600 text-white rounded-xl text-sm font-semibold hover:bg-violet-700 transition-colors"
        >
          Go to Plan Room
        </button>
      </div>
    );
  }

  const plan = generatedPlan;

  return (
    <div className="space-y-4 pb-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-gray-900">Trip Approval</h2>
          <p className="text-xs text-gray-500 mt-0.5">Generated by Sage · {new Date(plan.generatedAt).toLocaleDateString()}</p>
        </div>
        {leaderApproved && (
          <div className="flex items-center gap-1.5 bg-emerald-100 text-emerald-700 px-3 py-1.5 rounded-full text-xs font-bold border border-emerald-200">
            <CheckCircle2 className="w-3.5 h-3.5" /> Approved!
          </div>
        )}
      </div>

      {/* Plan Summary Card */}
      <div className="rounded-2xl overflow-hidden shadow-md border border-gray-100">
        {/* Hero gradient */}
        <div className="bg-gradient-to-r from-violet-600 via-purple-600 to-indigo-700 px-5 py-5 text-white">
          <div className="flex items-start gap-2">
            <Plane className="w-5 h-5 mt-0.5 opacity-80" />
            <div>
              <h3 className="text-xl font-bold">{plan.destination}</h3>
              <p className="text-sm opacity-80 mt-0.5">{plan.startDate} → {plan.endDate}</p>
            </div>
          </div>
        </div>

        {/* Details */}
        <div className="bg-white px-5 py-4 space-y-4">
          {/* Highlights */}
          <div>
            <h4 className="text-xs font-bold uppercase tracking-wide text-gray-400 mb-2 flex items-center gap-1.5">
              <MapPin className="w-3 h-3" /> Highlights
            </h4>
            <div className="flex flex-wrap gap-1.5">
              {plan.highlights.map((h, i) => (
                <span key={i} className="bg-violet-50 text-violet-700 border border-violet-100 rounded-full px-2.5 py-0.5 text-xs font-medium">
                  {h}
                </span>
              ))}
            </div>
          </div>

          {/* Budget */}
          <div className="flex items-center gap-3">
            <DollarSign className="w-4 h-4 text-amber-500 shrink-0" />
            <div>
              <p className="text-xs text-gray-500">Estimated Budget</p>
              <p className="text-sm font-bold text-gray-900">
                ${plan.budgetEstimateUSD.low.toLocaleString()} – ${plan.budgetEstimateUSD.high.toLocaleString()} USD
              </p>
            </div>
          </div>

          {/* Day by day preview */}
          {plan.dayByDay.length > 0 && (
            <div>
              <h4 className="text-xs font-bold uppercase tracking-wide text-gray-400 mb-2 flex items-center gap-1.5">
                <Calendar className="w-3 h-3" /> Itinerary Preview
              </h4>
              <div className="space-y-2">
                {plan.dayByDay.slice(0, 3).map(day => (
                  <div key={day.day} className="bg-gray-50 rounded-xl px-3 py-2.5 border border-gray-100">
                    <p className="text-xs font-bold text-violet-700 mb-1">Day {day.day} · {day.date}</p>
                    <div className="grid grid-cols-3 gap-1 text-[11px] text-gray-600">
                      <div><span className="text-gray-400">AM</span><br />{day.morning}</div>
                      <div><span className="text-gray-400">PM</span><br />{day.afternoon}</div>
                      <div><span className="text-gray-400">EVE</span><br />{day.evening}</div>
                    </div>
                    {day.hotel && <p className="text-[10px] text-gray-400 mt-1.5 flex items-center gap-1">🏨 {day.hotel}</p>}
                  </div>
                ))}
                {plan.dayByDay.length > 3 && (
                  <p className="text-xs text-gray-400 text-center">+{plan.dayByDay.length - 3} more days in full itinerary</p>
                )}
              </div>
            </div>
          )}

          {/* Notes */}
          {plan.notes && (
            <p className="text-xs text-gray-500 italic border-l-2 border-gray-200 pl-3">{plan.notes}</p>
          )}
        </div>
      </div>

      {/* Member votes */}
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm px-4 py-4">
        <h4 className="text-xs font-bold uppercase tracking-wide text-gray-400 mb-3">Member Votes</h4>

        {teamDetail ? (
          <div className="space-y-2">
            {teamDetail.members.map(m => {
              const mVote = memberVotes[m.userId];
              const mIsLeader = m.userId === leaderId;
              const mIsCoLeader = m.userId === coLeaderId;
              const isMe = m.userId === currentUserId;

              return (
                <div key={m.userId} className={`flex items-center gap-3 p-2 rounded-xl transition-colors ${isMe ? 'bg-violet-50 border border-violet-100' : 'bg-gray-50'}`}>
                  {/* Avatar */}
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold shrink-0
                    ${mIsLeader ? 'bg-amber-100 text-amber-700' : mIsCoLeader ? 'bg-blue-100 text-blue-700' : 'bg-gray-200 text-gray-600'}`}>
                    {(m.displayName || m.email || '?').charAt(0).toUpperCase()}
                  </div>

                  {/* Name + role */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-1">
                      <span className="text-xs font-semibold text-gray-900 truncate">
                        {m.displayName?.split(' ')[0] || m.email?.split('@')[0] || 'User'}
                      </span>
                      {mIsLeader && <Crown className="w-3 h-3 text-amber-500 shrink-0" />}
                      {mIsCoLeader && <Shield className="w-3 h-3 text-blue-500 shrink-0" />}
                      {isMe && <span className="text-[9px] text-violet-500 font-bold">(you)</span>}
                    </div>
                  </div>

                  {/* Vote status or vote buttons */}
                  {isMe && !mVote ? (
                    <div className="flex gap-1.5 shrink-0">
                      <button
                        onClick={() => setVote(currentUserId, 'approve')}
                        className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-emerald-500 text-white text-[11px] font-bold hover:bg-emerald-600 transition-colors"
                      >
                        <ThumbsUp className="w-3 h-3" /> Approve
                      </button>
                      <button
                        onClick={() => setVote(currentUserId, 'reject')}
                        className="flex items-center gap-1 px-2.5 py-1 rounded-lg bg-red-100 text-red-600 text-[11px] font-bold hover:bg-red-200 transition-colors border border-red-200"
                      >
                        <ThumbsDown className="w-3 h-3" /> Reject
                      </button>
                    </div>
                  ) : mVote ? (
                    <div className={`flex items-center gap-1 text-[11px] font-bold shrink-0 ${mVote === 'approve' ? 'text-emerald-600' : 'text-red-500'}`}>
                      {mVote === 'approve' ? <CheckCircle2 className="w-3.5 h-3.5" /> : <XCircle className="w-3.5 h-3.5" />}
                      {mVote === 'approve' ? 'Approved' : 'Rejected'}
                    </div>
                  ) : (
                    <span className="text-[11px] text-gray-400 shrink-0">Pending…</span>
                  )}
                </div>
              );
            })}
          </div>
        ) : (
          <p className="text-sm text-gray-400">Loading members…</p>
        )}

        {/* Vote tally */}
        {totalVotes > 0 && (
          <div className="mt-3 flex items-center gap-3 pt-3 border-t border-gray-100">
            <div className="flex-1 bg-gray-100 rounded-full h-2 overflow-hidden">
              <div
                className="h-full bg-emerald-500 rounded-full transition-all duration-500"
                style={{ width: `${totalVotes > 0 ? (approveCount / totalVotes) * 100 : 0}%` }}
              />
            </div>
            <span className="text-xs font-bold text-emerald-600">{approveCount} ✓</span>
            <span className="text-xs font-bold text-red-400">{rejectCount} ✗</span>
          </div>
        )}
      </div>

      {/* Final Approve — leader or co-leader only */}
      {!leaderApproved ? (
        isAuthorized ? (
          <div className="bg-gradient-to-r from-violet-50 to-purple-50 border border-violet-200 rounded-2xl px-4 py-4">
            <h4 className="text-sm font-bold text-violet-800 mb-1 flex items-center gap-1.5">
              <Crown className="w-4 h-4 text-amber-500" />
              Final Approval
            </h4>
            <p className="text-xs text-violet-600 mb-3">
              As the {currentUserId === leaderId ? 'Team Leader' : 'Co-Leader'}, you have the final say. Approving will unlock the Travel itinerary.
            </p>
            <button
              onClick={handleFinalApprove}
              disabled={approving}
              className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-violet-600 to-purple-700 hover:from-violet-700 hover:to-purple-800 text-white font-bold text-sm py-3.5 rounded-xl shadow-md transition-all duration-200 active:scale-[0.98] disabled:opacity-60"
            >
              {approving ? (
                <><Loader2 className="w-4 h-4 animate-spin" /> Approving…</>
              ) : (
                <><CheckCircle2 className="w-4 h-4" /> Give Final Approval &amp; Unlock Travel</>
              )}
            </button>
          </div>
        ) : (
          <div className="bg-gray-50 border border-gray-200 rounded-2xl px-4 py-3 text-center">
            <p className="text-xs text-gray-500">Waiting for the Team Leader or Co-Leader to give final approval.</p>
          </div>
        )
      ) : (
        <div className="flex items-center justify-center gap-2 py-3 bg-emerald-50 border border-emerald-200 rounded-2xl">
          <CheckCircle2 className="w-5 h-5 text-emerald-600" />
          <p className="text-sm font-bold text-emerald-700">Plan approved! Head to Travel →</p>
          <button
            onClick={() => router.push('/travel-plan')}
            className="ml-2 px-3 py-1 bg-emerald-600 text-white rounded-lg text-xs font-bold hover:bg-emerald-700 transition-colors"
          >
            View Itinerary
          </button>
        </div>
      )}
    </div>
  );
}
